site_name: John L. Whiteman
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - search.suggest
    - search.highlight
  font:
    text: Roboto
  highlightjs: true
  locale: en
  palette:
    scheme: saltlick
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
nav:
    - home: index.md
    - certs:
      - oswp:
        - attacks:
          - cracking:
            - aircrack-ng: certs/oswp/attacks/cracking/aircrack-ng.md
            - cowpatty: certs/oswp/attacks/cracking/cowpatty.md
            - crunch: certs/oswp/attacks/cracking/crunch.md
            - john-the-ripper: certs/oswp/attacks/cracking/john-the-ripper.md
            - pyrit: certs/oswp/attacks/cracking/pyrit.md
          - wep:
            - arp-request-replay: certs/oswp/attacks/wep/arp-request-replay.md
            - bypassing-wep-shared-key-auth: certs/oswp/attacks/wep/bypassing-wep-shared-key-auth.md
            - deauthentication: certs/oswp/attacks/wep/deauthentication.md
            - fake-authentication: certs/oswp/attacks/wep/fake-authentication.md
            - fragmentation: certs/oswp/attacks/wep/fragmentation.md
            - interactive-packet-replay: certs/oswp/attacks/wep/interactive-packet-replay.md
            - korek-chopchop: certs/oswp/attacks/wep/korek-chopchop.md
        - equipment: certs/oswp/equipment.md
        - tools:
          - airmon-ng: certs/oswp/tools/airmon-ng.md
          - airodump-ng: certs/oswp/tools/airodump-ng.md
          - aireplay-ng: certs/oswp/tools/aireplay-ng.md
          - aircrack-ng: certs/oswp/tools/aircrack-ng.md
          - airdecap-ng: certs/oswp/tools/airdecap-ng.md
          - if-ip-iw: certs/oswp/tools/if-ip-iw.md
    - doctools:
      - charts: doctools/charts/charts.md
      - kroki: doctools/kroki/kroki.md
      - html: doctools/html/html.md
      - markdown: doctools/markdown/markdown.md
      - mkdocs: doctools/mkdocs/mkdocs.md
      - slidev: doctools/slidev/slidev.md
    - linux:
      - bg-fg-jobs: linux/bg-fg-jobs.md
      - screen: linux/screen.md
    - about: about.md
plugins:
  - charts
  - kroki
  - search
repo_url: https://johnlwhiteman.github.io/
extra_javascript:
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
extra_css:
  - css/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css